lily_profile:
    pattern:  /profile
    defaults: { _controller: LilyUserBundle:Profile:index }

lily_users_admin:
    pattern:  /users
    defaults: { _controller: LilyUserBundle:User:index }

lily_user_api:
    resource: "@LilyUserBundle/Controller/UserController.php"
    type:     rest
    prefix:   /api/user