lily_profil:
    pattern:  /profil
    defaults: { _controller: LilyUserBundle:Profil:index }

lily_profil_api:
    resource: "@LilyUserBundle/Controller/ProfilController.php"
    type:     rest
    prefix:   /api/user

lily_users:
    pattern:  /users
    defaults: { _controller: LilyUserBundle:Admin:index }

lily_users_api:
    resource: "@LilyUserBundle/Controller/AdminController.php"
    type:     rest
    prefix:   /api/user/admin