lily_profile:
    pattern:  /profile
    defaults: { _controller: LilyUserBundle:Index:profile }

lily_users_admin:
    pattern:  /users
    defaults: { _controller: LilyUserBundle:Index:users }

lily_users_api:
    resource: "@LilyUserBundle/Controller/UserController.php"
    type:     rest
    prefix:   /api
    
lily_groups_api:
    resource: "@LilyUserBundle/Controller/GroupController.php"
    type:     rest
    prefix:   /api