parameters:
#    lily_user.example.class: Lily\UserBundle\Example

services:
#    lily_user.example:
#        class: %lily_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
