parameters:
#    lily_user.example.class: Lily\UserBundle\Example

services:
    RedirectAfterLogin:
        class: Lily\UserBundle\Redirection\UserRedirection
        arguments: [@router, @security.context]