<?php

namespace Lily\KnowledgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalQuestionRepository extends EntityRepository
{
}
