<?php

namespace Lily\KnowledgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnansweredQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnansweredQuestionRepository extends EntityRepository
{
}
