lily_dashboard:
    pattern:  /dashboard
    defaults: { _controller: LilyBackOfficeBundle:Dashboard:index }
    
lily_statistics:
    pattern:  /statistics
    defaults: { _controller: LilyBackOfficeBundle:Statistics:index }
    
lily_statistiques_api:
    resource: "@LilyBackOfficeBundle/Controller/StatisticsController.php"
    type:     rest
    prefix:   /api/statistics

lily_config:
    pattern:  /config
    defaults: { _controller: LilyBackOfficeBundle:Config:index }
    
lily_config_api:
    resource: "@LilyBackOfficeBundle/Controller/ConfigController.php"
    type:     rest
    prefix:   /api/config
    
# lily_personnalisation:
#     pattern:  /personnalisation
#     defaults: { _controller: LilyBackOfficeBundle:Personnalisation:index }
#     
# lily_personnalisation_temp:
#     resource: "@LilyBackOfficeBundle/Controller/PersonnalisationController.php"
#     type:     annotation
#     
# lily_facturation:
#     pattern:  /facturation
#     defaults: { _controller: LilyBackOfficeBundle:Facturation:index }