parameters:
#    lily_back_office.example.class: Lily\BackOfficeBundle\Example

services:
#    lily_back_office.example:
#        class: %lily_back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
