parameters:
#    lily_back_office.example.class: Lily\BackOfficeBundle\Example

services:
    lily.twig.avatar_extension:
        class: Lily\BackOfficeBundle\Twig\AvatarExtension
        tags:
            - { name: twig.extension }
        arguments: [ "%cdn%" ]

    lily.twig.customerDir_extension:
        class: Lily\BackOfficeBundle\Twig\CustomerDirExtension
        tags:
            - { name: twig.extension }
        arguments: [ "%cdn%" ]

    lily.twig.avatarDir_extension:
        class: Lily\BackOfficeBundle\Twig\AvatarDirExtension
        tags:
            - { name: twig.extension }
        arguments: [ "%cdn%" ]
