parameters:
#    lily_back_office.example.class: Lily\BackOfficeBundle\Example

services:
    lily.twig.avatar_extension:
        class: Lily\BackOfficeBundle\Twig\AvatarExtension
        tags:
            - { name: twig.extension }
        arguments: [ "@doctrine.orm.default_entity_manager", "%cdn%" ]
