imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: resources/solarium.yml }
    - { resource: resources/memcached.yml }
    - { resource: resources/assetic.yml }
    - { resource: resources/framework.yml }
    - { resource: resources/jms.yml }
    - { resource: resources/doctrine.yml }
    - { resource: resources/mailer.yml }
    - { resource: resources/fos.yml }
    - { resource: resources/sensio.yml }
    - { resource: resources/stof.yml }
    - { resource: resources/mobiledetect.yml }
    - { resource: resources/flysystem.yml }