imports:
    - { resource: parameters_dev.yml }
    - { resource: security.yml }
    - { resource: resources_dev/solarium.yml }
    - { resource: resources_dev/memcached.yml }
    - { resource: resources_dev/assetic.yml }
    - { resource: resources_dev/framework.yml }
    - { resource: resources_dev/jms.yml }
    - { resource: resources_dev/doctrine.yml }
    - { resource: resources_dev/mailer.yml }
    - { resource: resources_dev/fos.yml }
    - { resource: resources_dev/sensio.yml }
    - { resource: resources_dev/stof.yml }
    - { resource: resources_dev/mobiledetect.yml }
    - { resource: resources_dev/flysystem.yml }