lily_root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: http://saio.fr

lily_media:
    resource: "@LilyMediaBundle/Resources/config/routing.yml"
    prefix:   /

lily_chat:
    resource: "@LilyChatBundle/Resources/config/routing.yml"
    prefix:   /

lily_knowledge:
    resource: "@LilyKnowledgeBundle/Resources/config/routing.yml"
    prefix:   /
    
lily_statistics:
    resource: "@LilyStatisticsBundle/Resources/config/routing.yml"
    prefix:   /

lily_app:
    resource: "@LilyAppBundle/Resources/config/routing.yml"
    prefix:   /app

lily_admin:
    resource: "@LilyAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

lily_back_office:
    resource: "@LilyBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /
    
lily_user:
    resource: "@LilyUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /