lily_home:
    resource: "@LilyHomePageBundle/Resources/config/routing.yml"
    prefix:   /

lily_chat:
    resource: "@LilyChatBundle/Resources/config/routing.yml"
    prefix:   /lily/chat

lily_knowledge:
    resource: "@LilyKnowledgeBundle/Resources/config/routing.yml"
    prefix:   /lily

lily_api:
    resource: "@LilyApiBundle/Resources/config/routing.yml"

lily_admin:
    resource: "@LilyAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

lily_back_office:
    resource: "@LilyBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /lily

lily_user:
    resource: "@LilyUserBundle/Resources/config/routing.yml"
    prefix:   /lily

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile