security:
    encoders:
        Lily\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_CHAT_OPERATOR, ROLE_KNOWLEDGE_OPERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_CHAT_OPERATOR: [ROLE_USER]
        ROLE_KNOWLEDGE_OPERATOR: [ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        public:
            pattern:  ^/(_(profiler|wdt)|app|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
                csrf_parameter: _csrf_token
                always_use_default_target_path: false
                success_handler: RedirectAfterLogin
                target_path_parameter:          _target_path
                use_referer:                    false       
            logout:
                path: fos_user_security_logout
                target: http://saio.fr
            anonymous:    true

    access_control:
        - { path: ^/[^/]+/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/[^/]+/, role: ROLE_USER }

        - { path: ^/app, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/, role: ROLE_USER }