services:
    session.memcached:
        class: Memcached
        arguments:
            persistent_id: %session_prefix%
        calls:
            - [ addServer, [ %session_host%, %session_port% ]]
 
    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [@session.memcached, { prefix: %session_prefix%, expiretime: %session_lifetime% }]
