parameters:
#    lily_api.example.class: Lily\ApiBundle\Example

services:
#    lily_api.example:
#        class: %lily_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
