home_index:
    pattern:  /
    defaults: { _controller: LilyHomePageBundle:Saio:index }

home_lily:
    pattern:  /products
    defaults: { _controller: LilyHomePageBundle:Saio:products }

home_references:
    pattern:  /references
    defaults: { _controller: LilyHomePageBundle:Saio:references }

home_case_studies:
    pattern:  /case-studies
    defaults: { _controller: LilyHomePageBundle:Saio:caseStudies }

home_team:
    pattern:  /team
    defaults: { _controller: LilyHomePageBundle:Saio:team }

home_blog:
    pattern:  /blog
    defaults: { _controller: LilyHomePageBundle:Saio:blog }

home_articles:
    pattern:  /articles/{id}
    defaults: { _controller: LilyHomePageBundle:Saio:articles }

home_contact:
    pattern:  /contact
    defaults: { _controller: LilyHomePageBundle:Saio:contact }

home_disclaimer:
    pattern:  /disclaimer
    defaults: { _controller: LilyHomePageBundle:Saio:disclaimer }

home_recruitment:
    pattern:  /recruitment
    defaults: { _controller: LilyHomePageBundle:Saio:recruitment }