home_index:
    pattern:  /{_locale}
    defaults: { _controller: LilyHomePageBundle:Saio:index, _locale: fr }

home_lily:
    pattern:  /{_locale}/products
    defaults: { _controller: LilyHomePageBundle:Saio:products, _locale: fr }

home_references:
    pattern:  /{_locale}/references
    defaults: { _controller: LilyHomePageBundle:Saio:references, _locale: fr }

home_case_studies:
    pattern:  /{_locale}/case-studies
    defaults: { _controller: LilyHomePageBundle:Saio:caseStudies, _locale: fr }

home_team:
    pattern:  /{_locale}/team
    defaults: { _controller: LilyHomePageBundle:Saio:team, _locale: fr }

home_blog:
    pattern:  /{_locale}/blog
    defaults: { _controller: LilyHomePageBundle:Saio:blog, _locale: fr }

home_articles:
    pattern:  /{_locale}/articles/{id}
    defaults: { _controller: LilyHomePageBundle:Saio:articles, _locale: fr }

home_contact:
    pattern:  /{_locale}/contact
    defaults: { _controller: LilyHomePageBundle:Saio:contact, _locale: fr }

home_disclaimer:
    pattern:  /{_locale}/disclaimer
    defaults: { _controller: LilyHomePageBundle:Saio:disclaimer, _locale: fr }