parameters:
#    lily_home_page.example.class: Lily\HomePageBundle\Example

services:
#    lily_home_page.example:
#        class: %lily_home_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
