# Lily/AdminBundle/Resources/config/admin.yml
services:
    sonata.admin.entreprise:
        class: Lily\AdminBundle\Admin\EntrepriseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entreprise", label: "Entreprise" }
        arguments:
            - ~
            - Lily\BackOfficeBundle\Entity\Entreprise
            - ~
        calls:
            - [ setTranslationDomain, [LilyAdminBundle]]