lily_faq:
    pattern:  /faq
    defaults: { _controller: LilyKnowledgeBundle:Faq:index }

lily_questions:
    pattern:  /questions
    defaults: { _controller: LilyKnowledgeBundle:Questions:index }

lily_redirections:
    pattern:  /redirections
    defaults: { _controller: LilyKnowledgeBundle:Redirections:index }

lily_categories_api:
    resource: "@LilyKnowledgeBundle/Controller/CategoriesController.php"
    type:     rest
    prefix:   /api/questions/categories

lily_tags_api:
    resource: "@LilyKnowledgeBundle/Controller/TagsController.php"
    type:     rest
    prefix:   /api/questions/tags

lily_faq_api:
    resource: "@LilyKnowledgeBundle/Controller/FaqController.php"
    type:     rest
    prefix:   /api

lily_questions_api:
    resource: "@LilyKnowledgeBundle/Controller/QuestionsController.php"
    type:     rest
    prefix:   /api/questions

lily_redirections_api:
    resource: "@LilyKnowledgeBundle/Controller/RedirectionsController.php"
    type:     rest
    prefix:   /api

lily_unsanswered_questions_api:
    resource: "@LilyKnowledgeBundle/Controller/UnansweredQuestionsController.php"
    type:     rest
    prefix:   /api/questions

lily_personal_questions_api:
    resource: "@LilyKnowledgeBundle/Controller/PersonalQuestionsController.php"
    type:     rest
    prefix:   /api/questions/personal