lily_faq:
    pattern:  /faq
    defaults: { _controller: LilyKnowledgeBundle:Faq:index }
    
lily_questions:
    pattern:  /questions
    defaults: { _controller: LilyKnowledgeBundle:Questions:index }    
    
lily_redirections:
    pattern:  /redirections
    defaults: { _controller: LilyKnowledgeBundle:Redirections:index }   

lily_categories_rest:
    resource: "@LilyKnowledgeBundle/Controller/CategoriesController.php"
    type:     rest
    prefix:   /questions/categories
    
lily_tags_rest:
    resource: "@LilyKnowledgeBundle/Controller/TagsController.php"
    type:     rest
    prefix:   /questions/tags
    
lily_faq_rest:
    resource: "@LilyKnowledgeBundle/Controller/FaqController.php"
    type:     rest
    prefix:   /faq
    
lily_questions_rest:
    resource: "@LilyKnowledgeBundle/Controller/QuestionsController.php"
    type:     rest
    prefix:   /questions 
    
lily_redirections_rest:
    resource: "@LilyKnowledgeBundle/Controller/RedirectionsController.php"
    type:     rest
    prefix:   /redirections 

lily_unsanswered_questions_rest:
    resource: "@LilyKnowledgeBundle/Controller/UnansweredQuestionsController.php"
    type:     rest
    prefix:   /questions/unanswered 

lily_personal_questions_rest:
    resource: "@LilyKnowledgeBundle/Controller/PersonalQuestionsController.php"
    type:     rest
    prefix:   /questions/personal