lily_knowledge:
    pattern:  /knowledge
    defaults: { _controller: LilyKnowledgeBundle:Index:knowledge }

lily_categories_api:
    resource: "@LilyKnowledgeBundle/Controller/CategoriesController.php"
    type:     rest
    prefix:   /api/questions

lily_tags_api:
    resource: "@LilyKnowledgeBundle/Controller/TagsController.php"
    type:     rest
    prefix:   /api/questions

lily_questions_api:
    resource: "@LilyKnowledgeBundle/Controller/QuestionsController.php"
    type:     rest
    prefix:   /api

lily_unsanswered_questions_api:
    resource: "@LilyKnowledgeBundle/Controller/UnansweredQuestionsController.php"
    type:     rest
    prefix:   /api/questions

lily_personal_questions_api:
    resource: "@LilyKnowledgeBundle/Controller/PersonalQuestionsController.php"
    type:     rest
    prefix:   /api/questions