parameters:
#    lily_knowledge.example.class: Lily\KnowledgeBundle\Example

services:
#    lily_knowledge.example:
#        class: %lily_knowledge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
