# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            # Lily users client
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

            # Client
            client:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_client_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    LilyAdminBundle: ~
                    LilyUserBundle: ~
                    
            # Client
            client:
                connection:       client
                mappings:
                    LilyBackOfficeBundle: ~
                    LilyAppBundle: ~
                    LilyKnowledgeBundle: ~
                    LilyChatBundle: ~
                    gedmo_loggable:
                        type: annotation
                        prefix: Lily\BackOfficeBundle\Loggable\Entity
                        dir: "%kernel.root_dir%/../src/Lily/BackOfficeBundle/Loggable/Entity"
                        is_bundle: false
                dql:
                       datetime_functions:
                                timediff: Lily\BackOfficeBundle\DoctrineFunction\TimeDiff
                                time_to_sec: Lily\BackOfficeBundle\DoctrineFunction\TimeToSec
                                unix_timestamp: Lily\BackOfficeBundle\DoctrineFunction\UnixTimestamp
                                round: Lily\BackOfficeBundle\DoctrineFunction\Round