# Memcached bundle
lsw_memcache:
    session:
        client: default
        prefix: "session_"
        ttl: 86400
        locking: true
        spin_lock_wait: 150000
    clients:
        default:
            hosts:
              - { dsn: 172.16.0.3 , port: 11211 }
            options:
                compression: true
                serializer: json
                prefix_key: ""
                hash: default
                distribution: consistent
                libketama_compatible: true
                buffer_writes: true
                binary_protocol: true
                no_block: true
                tcp_nodelay: false
                socket_send_size: 4096
                socket_recv_size: 4096
                connect_timeout: 1000
                retry_timeout: 0
                send_timeout: 0
                recv_timeout: 0
                poll_timeout: 1000
                cache_lookups: false
                server_failure_limit: 0
    doctrine:
        metadata_cache:
            client: default
            entity_manager: [default, client]
        result_cache:
            client: default
            entity_manager: [default, client]
            prefix: "result_"
        query_cache:
            client: default
            entity_manager: [default, client]