lily_app_index:
    pattern:  /{licence}
    defaults: { _controller: LilyAppBundle:App:index }

lily_app_js_index:
    pattern:  /widget/{licence}
    defaults: { _controller: LilyAppBundle:App:widget }

lily_app_rest:
    resource: "@LilyAppBundle/Controller/AppController.php"
    type:     rest
    prefix:   /api

lily_app_avi_rest:
    resource: "@LilyAppBundle/Controller/AviController.php"
    type:     rest
    prefix:   /api

lily_demo_index:
    pattern:  /demo/{licence}/{url}
    defaults: { _controller: LilyAppBundle:Demo:index }
