parameters:
#    lily_app.example.class: Lily\AppBundle\Example

services:
#    lily_app.example:
#        class: %lily_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]