parameters:
#    lily_enterprise.example.class: Lily\EnterpriseBundle\Example

services:
#    lily_enterprise.example:
#        class: %lily_enterprise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
