<?php

namespace Lily\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * NotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogNotationRepository extends EntityRepository
{
	
	public function satisfaction($from, $to, $interval) {
		
		$qb = $this->createQueryBuilder('n');
        
        // UNIX_TIMESTAMP is a personalized dql function, calling the correspondant sql function
        $qb->select('avg(n.satisfied) as value')
           ->where('UNIX_TIMESTAMP(n.date) >= :start')
           ->setParameter('start', $from)
           ->andWhere('UNIX_TIMESTAMP(n.date) < :end')
           ->setParameter('end', $to)
           ->andWhere('n.satisfied IS NOT NULL');
		
        if($interval) {
           $qb->addSelect('ROUND(UNIX_TIMESTAMP(n.date)/(:interval)) as intervalId')
              ->setParameter('interval', $interval)
              ->groupBy('intervalId');
              
            return $qb->getQuery()->getResult();
        } else {
            return $qb->getQuery()->getSingleScalarResult() ?: 0;
        }	          
		
	}
	
}
