<?php

namespace Lily\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogUnansweredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogUnansweredRepository extends EntityRepository
{	
}
