<?php

namespace Lily\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogConnectionRepository extends EntityRepository
{
	public function uniqueVisitors($from, $to) {
		
		$qb = $this->createQueryBuilder('c');
		
		$qb->select('count(distinct c.session)')
		   ->where('c.date >= :from')
		   ->setParameter('from', $from)
		   ->andWhere('c.date <= :to')
		   ->setParameter('to', $to);
		
		return $qb->getQuery()
		          ->getSingleScalarResult();
		          
	}
}
