<?php

namespace Lily\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRedirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRedirectionRepository extends EntityRepository
{
	public function redirections($from, $to) {
		
		$qb = $this->createQueryBuilder('r');
		
		$qb->select('count(r)')
		   ->where('r.date >= :from')
		   ->setParameter('from', $from)
		   ->andWhere('r.date <= :to')
		   ->setParameter('to', $to);
		
		return $qb->getQuery()
		          ->getSingleScalarResult();
		          
	}
	
	public function mails($from, $to) {
		
		$qb = $this->createQueryBuilder('r');
		
		$qb->select('count(r)')
		   ->where('r.date >= :from')
		   ->setParameter('from', $from)
		   ->andWhere('r.date <= :to')
		   ->setParameter('to', $to)
		   ->andWhere('r.canal = :canal')
		   ->setParameter('canal', 'mail');
		
		return $qb->getQuery()
		          ->getSingleScalarResult();
		          
	}
	
	public function phones($from, $to) {
		
		$qb = $this->createQueryBuilder('r');
		
		$qb->select('count(r)')
		   ->where('r.date >= :from')
		   ->setParameter('from', $from)
		   ->andWhere('r.date <= :to')
		   ->setParameter('to', $to)
		   ->andWhere('r.canal = :canal')
		   ->setParameter('canal', 'tel');
		
		return $qb->getQuery()
		          ->getSingleScalarResult();
		          
	}
	
}
