<?php

namespace Lily\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogChatRepository extends EntityRepository
{
}
