parameters:
#    lily_statistics.example.class: Lily\StatisticsBundle\Example

services:
#    lily_statistics.example:
#        class: %lily_statistics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
