# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [LilyBackOfficeBundle, LilyApiBundle, LilyChatBundle, LilyKnowledgeBundle, LilyUserBundle, LilyHomePageBundle, LilyAdminBundle]
    node: /usr/bin/node
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            apply_to: "\.js$"
        uglifycss:
            bin: /usr/bin/uglifycss
            apply_to: "\.css$"