oneup_flysystem:
    adapters:
        cdn:
            ftp:
                host: cdn.saio.fr
                port: 21
                username: saio
                password: qyH26i$8
                root: /cdn.saio.fr
                passive: ~
    filesystems:
        cdn:
            adapter: cdn
            mount: cdn