oneup_flysystem:
    adapters:
        cdn:
            ftp:
                host: "%cdn%"
                port: 21
                username: "%ftp_username%"
                password: "%ftp_password%"
                root: "%ftp_root%"
                passive: true
    filesystems:
        cdn:
            adapter: cdn
            mount: cdn