knp_gaufrette:
    adapters:
        cdn:
            ftp:
                host: cdn.saio.fr
                username: saio
                password: qyH26i$8
                directory: /cdn.saio.fr
                create: true
                mode: FTP_BINARY