# StofDoctrine    
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        client: 
            loggable: true
            timestampable: true
            sortable: true
    class:
        loggable: Lily\BackOfficeBundle\Loggable\LoggableListener