lily_chat:
    pattern:  /
    defaults: { _controller: LilyChatBundle:Operator:index }

lily_chat_rest:
    resource: "@LilyChatBundle/Controller/OperatorController.php"
    type:     rest
    prefix:   /
